# Generated by Django 5.1.5 on 2025-01-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usertoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
