# Generated by Django 5.1.5 on 2025-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_usertoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
