# Generated by Django 5.1.5 on 2025-01-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_group_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ManyToManyField(related_name='friend', to='chat.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.member')),
            ],
        ),
    ]
