# Generated by Django 5.1.5 on 2025-01-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_id', models.CharField(default=2011644, max_length=255, unique=True)),
                ('image', models.ImageField(default='https://i.pinimg.com/736x/75/46/fe/7546feb15edb3f2d46f22a737042b552.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(default='Enjoying Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.member')),
            ],
        ),
    ]
