# Generated by Django 5.1.5 on 2025-01-25 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_profile_image_alter_profile_up_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='up_id',
            field=models.CharField(default=3869249, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='chat.member'),
        ),
    ]
